### ISSUE TITLE
Modal when game is not started

### ISSUE THREAD

**Issue by pieza** [pieza/zketcher#24]
## Description
Show a message like "Press start button to play" when the game is not init.

## Acceptance Criteria
- The message should be displayed at /play/{room_id} (game component)
- Only display if the play button is not pressed.
- All members of the room should see the message.

### Good to have
- Would be great if this component could be reused for other messages types.

This is an example of where the message should be:
![image](https://user-images.githubusercontent.com/19609958/93509265-b87e4d00-f8dc-11ea-9cee-dc154c8cce55.png)

**Comment by thePlebDev** [comment]
is this still up for grabs? I would like to work on this

**Comment by pieza** [comment]
sure @thePlebDev, let me know if you want to meet or if you have any doubt, thanks for the help!

**Comment by thePlebDev** [comment]
<img width="1127" alt="ZketcherNotification" src="https://user-images.githubusercontent.com/47083513/93614170-30657980-f9a8-11ea-8533-36270263a3fd.png">

this is just a basic mock up so you can give me details on how you would like it to look. like where do you want it positioned on the screen and that sort of stuff. If you dont have any specifics for the design, Ill just keep it in theme with the whole website.

**Comment by pieza** [comment]
Looks good, I don't have any specifics, I'll just add more padding on top and bottom, and a space for an image, feel free to add any ideas for the design, thanks!

![image](https://user-images.githubusercontent.com/19609958/93618606-bb3c7900-f994-11ea-8f84-a927497ce274.png)

**Comment by thePlebDev** [comment]
ok, will do boss

**Comment by thePlebDev** [comment]
<img width="1126" alt="ZketcherNotificationUpdate" src="https://user-images.githubusercontent.com/47083513/93671331-6bcf7900-fa78-11ea-9971-a8b29bb81555.png">

just an update on how it looks. 
1)There is click detection using react Refs so it will close if the user clicks on the X or outside the modal. 
2)Also, it has a css animation that will make the modal grow and shrink
3) The entire background gets blurred when modal is active

**Comment by pieza** [comment]
Looking good! :)
